server:
  port: 6666

spring:
  activemq:
    broker-url: tcp://localhost:61616 #自己MQ服务器地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false=Queue true=Topic 默认Topic

#自己定义队列名称
mytopic: boot-activemq-topic
